name: Deploy GitHub Pages

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - name: Increase max file handles (attempt 2)
        run: echo fs.inotify.max_user_watches=128000 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Install dependencies
        run: sudo apt-get install jq shellcheck
      - name: Test
        run: shellcheck test.sh && ./test.sh
      - name: Build Pages
        run: node --max-old-space-size=8192 ./src/build-pages.js
      - name: List generated files
        run: ls -al dist/v1/phone/*
      - name: Size Report
        run: 'echo "API file size: $(du -hs dist/v1 | cut -f1)"'
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist/'
