name: Deploy GitHub Pages

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
      - run: whoami
      - run: bash -c ulimit -n
      - run: bash -c ulimit -Hn
      - run: ulimit -n
      - run: ulimit -Hn
      - run: sudo sed -i 's/nofile 65536/nofile 128000/' /etc/security/limits.conf
      - run: ulimit -n
      - run: ulimit -Hn
      - run: bash -c ulimit -n
      - run: bash -c ulimit -Hn
      - run: ulimit -a
      - run: cat /etc/systemd/user.conf
      - run: cat /etc/security/limits.conf
      - name: Install dependencies
        run: sudo apt-get install jq shellcheck
      - name: Test
        run: node --max-old-space-size=8192 ./src/test-file-limits.js
